eamigo86/graphene-django-extras

graphene_django_extras/types.py

DjangoListObjectType seems to ignore only_fields. This just supplies the valid parameter to the relevant factory.

DjangoListObjectType should now honor only_fields.

---

graphene_django_extras/types.py

For example, for the common case where the Serializer has per-request custom behavior, users can instruct `DjangoSerializerType` to pass the request through context:
```python
class UserType(DjangoSerializerType):
@classmethod
def get_serializer_kwargs(cls, root, info, **kwargs):
return {'context': {'request': info.context}}
class Meta:
serializer_class = UserSerializer
```
I only implemented this for `DjangoSerializerType` and not `DjangoSerializerMutation`.

Allow for custom initialization of Serializers

---

graphene_django_extras/fields.py

This update will pass info.context into the filterset_class for DjangoListObjectField and DjangoFilterPaginateListField and be available as self.request per the Django FilterSet convention. This should resolve issue #28

Pass info.context to filterset as request

---

README.md
README.rst

Small typo in README files import fixed. (A few whitespaces improvement go for free)
¡Muchas gracias!

Fix typo in README.* files

---

graphene_django_extras/paginations/fields.py
graphene_django_extras/paginations/pagination.py

Thanks for this super helpful library! This is just a quick update that should add an input field 'order' for use with the LimitOffsetPagination class. This input will be passed to the queryset.order_by() method to sort results before pagination and so uses the same syntax as the Django method, ie. order: "id" or order: "-id".

Add logic to support ordering of queryset in LimitOffsetPagination.

---

graphene_django_extras/utils.py

Imports _resolve_model (for Django<1.9) only when it actually is running in Django<1.9

---

graphene_django_extras/utils.py

Fixed a bug where many-to-many/one-to-many relation fields could be mistakenly added to select_related() in queryset factory

Fixed a bug in queryset factory

---

graphene_django_extras/types.py

https://github.com/eamigo86/graphene-django-extras/issues/48

DjangoInputObjectType doesn't allow overwriting model fields fix

---

graphene_django_extras/tests/queries.py
graphene_django_extras/tests/test_fields.py
testproject/filtersets.py

There's a failing tests : 
```
======================================================================
ERROR: test_field (graphene_django_extras.tests.test_fields.DjangoFilterPaginateListFieldTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/zulu/projects/graphene-django-extras/graphene_django_extras/tests/test_fields.py", line 30, in test_field
self.assertIn('results', data['data']['allUsers1'])
File "/usr/lib/python3.5/unittest/case.py", line 1076, in assertIn
if member not in container:
TypeError: argument of type 'NoneType' is not iterable
----------------------------------------------------------------------
```
Do you have an idea why ?

Added tests for Query's fields

---

setup.py

The _django-filter_ package version should be pinned
Until this gets fixed: https://github.com/graphql-python/graphene-django/issues/464
As in here: https://github.com/graphql-python/graphene-django/commit/f0705e2c25a07024334ea810562d263496ebbd9e
:beers:

pin version of django-filter package

---

README.md
README.rst
setup.py

`dateutils` is listed as a dependency but never used in the project. Instead, imports come from `dateutil`, which maps to the `python-dateutil` name on PyPI. This currently works because `python-dateutil` is a dependency of `dateutils`, but the `extras_require` and documentation should be updated to reflect the correct library being used.

Replace dateutils dependency with python-dateutil

---

graphene_django_extras/paginations/fields.py
graphene_django_extras/paginations/pagination.py

This is a pretty small change. I noticed some blatantly incorrect grammar in my GraphiQL client, so I figured I'd propose a fix.
Please excuse the sloppy commit history, I didn't clone my fork locally. Since they're grammar edits I just used the github interface.

Fix the grammar for the field ordering description

---

graphene_django_extras/utils.py

This change adds explicit handling for `InlineFragment`s when resolving querysets within `list_resolver`'s.
Take the following pure `graphene` example:
```python
import graphene
class ComplexDataType(graphene.ObjectType):
field1 = graphene.String()
field2 = graphene.String()
class OptionInterface(graphene.Interface):
name = graphene.String()
class OptionOneType(graphene.ObjectType):
class Meta:
interfaces = (OptionInterface,)
class OptionTwoType(graphene.ObjectType):
class Meta:
interfaces = (OptionInterface,)
special_field1 = graphene.Field(ComplexDataType)
class Query(graphene.ObjectType):
options = graphene.List(OptionInterface)
def resolve_options(self, _info):
return [OptionOneType(name='Display'), OptionTwoType(name='Video', special_field1=ComplexDataType(field1="asdf"))]
schema = …
```

Add handling for InlineFragments

---

graphene_django_extras/fields.py

I put new method `get_queryset`
It let developers manipulate the QuerySet with override the total `list_resolver`.
Else, it's not possible to filter on returned QS as it is already ordered/limited.

Made get_queryset

---

graphene_django_extras/types.py

There is currently no way to customize the `results` keyword in graphql collections. This allows the user to customize this return type for `DjangoSerializerTypes` (what we are using this for) by passing `results_field_name` to the factory function. An example implementation:
```
class MyModelType(DjangoSerializerType):
class Meta:
description = "Model type definition "
serializer_class = MyModelSerializer
pagination = LimitOffsetGraphqlPagination(default_limit=20)
filterset_class = MyModelFilter
results_field_name = 'items'
```

Add results_field_name to DjangoSerializerType factory function

---

graphene_django_extras/paginations/pagination.py

When page_size_query_param is set in the constructor but a query does not contain the param, fall back to self.page_size also given in the constructor.
It would probably make sense to comment in the ValueError on line 173 because page_size should never be None expect for invalid constructor parameters.

page pagination: fall back to default page_size when page_size_query_param is missing in query

---

graphene_django_extras/mutation.py
graphene_django_extras/types.py

Just a quick fix because of this change to graphene-django:
https://github.com/graphql-python/graphene-django/issues/520

Fix:  Update import of ErrorType 

---

graphene_django_extras/directives/date.py
graphene_django_extras/directives/list.py
graphene_django_extras/directives/string.py

Ths is not working for my environment that is base on django project.
```
graphene==2.1.8
graphene-django==2.10.0
graphene-django-extras==0.4.8
graphql-core==2.3.2
```
after change naming param `type` to `type_` on GraphQLArgument initialization part, it working well!
Thank you Sir :)

Fix unexpected keyword argument 'type' error

---

graphene_django_extras/converter.py
graphene_django_extras/types.py

Fixed bug on using non-paginated fields in `DjangoSerializerType`. Fix for #124

Fixed bug with non-paginated fields

---

graphene_django_extras/types.py

Fixed the bug which was blocked usage inherited classes as the declared graphene type, see example below.
```
class DjangoModel(models.Model):
name = models.CharField(unique=True)
uuid = models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False, unique=True)
class MyModel(DjangoModel):
def some_custom_logic():
pass
class Meta:
proxy = True
class ModelType(DjangoObjectType):
class Meta:
model = Model
class MyMutation(graphene.Mutation):
model = graphene.Field(ModelType, required=False)
@classmethod
def mutate(cls, root, info, deployment_id):
return cls(model=MyModel())
```

Fixed bug with model type validation in DjangoObjectType

---

graphene_django_extras/directives/date.py
graphene_django_extras/directives/list.py
graphene_django_extras/directives/string.py

There is an issue with latest version of this package. 
I think there is an issue in the way `GraphQLArgument` (from graphql-core) is called. 
This should fix #143

Fix the way GraphQLArgument function is called

---

graphene_django_extras/types.py

**Background:**
- Last year, `graphene-django` added a method to `DjangoObjectType` called `get_queryset` ([commit](https://github.com/graphql-python/graphene-django/commit/0a5020bee15b2ef04ddbd86ec903b6d87c59aa05#diff-6926ea790e42fa924302b75462dfef72R137))
- A few months later, they changed how `list_resolver` worked in `DjangoListField` ([commit](https://github.com/graphql-python/graphene-django/commit/fea9b5b194c9ec7dc864143b918c73931f652ef4#diff-4693e93918b75fd2ff08fbe53fec5118R44))
- This hasn't been an issue until `v2.10.0` because `get_queryset` was only called when `if queryset is None`, which is never true (I guess 🤔)
**Issue:**
In `v2.10.0`, they refactored `list_resolver` in `DjangoListField` ([commit](https://github.com/graphql-python/graphene-django/commit/b4e34a5794edd430f250 …

Fix missing get_queryset method in DjangoObjectType

---

graphene_django_extras/converter.py
graphene_django_extras/fields.py
graphene_django_extras/middleware.py
graphene_django_extras/mutation.py
graphene_django_extras/types.py
graphene_django_extras/utils.py
poetry.lock
pyproject.toml
tests/client.py
tests/test_fields.py

A few updates in order to bring basic graphene v3 compatibility.
This obviously need a bit of review / testing.
Related graphql-python/graphene-django#705
The tests are currently broken, I guess because directives are broken as well. They use promises, for which support has been dropped in graphql core v3.

[WIP] Bring graphene v3 compatibility 

---

poetry.lock
pyproject.toml

current `django-filter` version is not compatible with the new latest calver versioning.
See https://github.com/eamigo86/graphene-django-extras/pull/191 comments for context

Update django-filter dependency to 22.1

---

.github/workflows/cicd.yaml
README.md
README.rst
graphene_django_extras/fields.py
pyproject.toml
tox.ini

Hi, I’m proposing a small compatibility update that lets `graphene-django-extras` work smoothly with Django 5 and `graphene-django` 3+ without changing public APIs or behavior.
**What changed:**
pyproject.toml: relaxed django-filter constraint to allow versions compatible with Django 5.
graphene_django_extras/fields.py: overridden DjangoListField.type to delegate to the base graphene.Field implementation and avoid the strict assertion introduced in graphene-django 3 that expects the core DjangoObjectType. Extras defines its own DjangoObjectType, so the core check can incorrectly reject it.
Why this is safe
**Scope-limited:** only affects extras’ DjangoListField; core graphene_django.fields.DjangoListField is untouched.
No API changes: the returned GraphQL type remains the declared type; …

Support Django 5 (DLF.type check and django-filter constraint)
